version: '3.8'

services:
  frontend-app:
    build: ./projeto-nextjs-mvvidros
    container_name: mvvidros-frontend
    environment:
      - WHATSAPP_API_URL=http://whatsapp-bot:3001/api/send-pdf
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    restart: unless-stopped
    depends_on:
      - whatsapp-bot

  whatsapp-bot:
    build: ./api-whatsapp-mvvidros
    container_name: mvvidros-bot
    volumes:
      - .wwebjs_auth:/app/.wwebjs_auth 
    restart: unless-stopped